baseURL = "https://richardphelps.netlify.app/"
title = "Supersonic"
description = "Lorem Ipsum"
languageCode = "en-ca"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[build]
writeStats = true
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = "1"

[[menu.main]]
name = "About"
url = "/#about/"
weight = "2"

[[menu.main]]
name = "The Book"
url = "#the-book/"
weight = "3"

[[menu.main]]
name = "Free Chapter"
url = "#free-chapter/"
weight = "4"

[[menu.main]]
name = "Purchase"
url = "#purchase/"
weight = "5"

[params]
gtm = "#"
servicename = "WebDesign"
googlemap = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10486.075597019064!2d-125.5296457!3d48.9245577!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x231041e6ea05c1b5!2sSteam%20Train%20Creative!5e0!3m2!1sen!2sca!4v1626282835512!5m2!1sen!2sca"
sitename = "Supersonic Template"
usebasin = "#"
videoOn = false
description = "Lorem ipsum"

[params.schema]
ogimage = "/img/supersonicsites-logo-final-750x450-1.png"
logofooter = "/img/supersonicsites-logo-final-750x450-1.png"
city = "Vancouver"
logo = "/img/supersonicsites-1.png"
reservation = true
phone = "+1-888-321-BOOM"
priceRange = "$$$"
region = "BC"
country = "Canada"
postalcode = "V5V 3N5"
type = "WebDesign"
openinghour = "Mo-Sa: 10-6"
email = "hello@supersonicsites.com"
address1 = "3622 Main Street"
address2 = "#"
address_toggle = true

[params.social]
facebook = "#"
twitter = "#"
pinterest = "#"
instagram = "/"
linkedin = "#"

[[params.hours]]
hours = "Mon to Sat: 10AM to 6PM"

[[params.hours]]
hours = "Sun: CLOSED"

[module]

    [[module.mounts]]
        source = "assets"
        target = "assets"

    [[module.mounts]]
        source = "./node_modules/alpinejs/dist/alpine.js"
        target = "assets/js/alpine.js"

    [[module.mounts]]
        source = "./node_modules/lazysizes/lazysizes.js"
        target = "assets/js/lazysizes.js"